data:
  build: ./data
  volumes:
    - /data

db:
  image: redis
  ports:
    - "6379:6379"
  volumes_from:
    - data

# Keep this as the last service so that the ./bin/start script
# can parse the other services that it links to.
#
web:
  build: ./app
  command: npm start
  ports:
    - "1337:1337"
  links:
    - db
